name: Build and push docker image to registers

on:
  workflow_call:
    inputs:
      APP_IMAGE_NAME:
        required: true
        type: string
    secrets:
      HARBOR_URL:
        required: true
      HARBOR_USER:
        required: true
      HARBOR_PASSWORD:
        required: true
      SSH_PRIVATE_KEY:
        required: true

      WEBPACK_SENTRY_AUTH_TOKEN:
        required: true
      WEBPACK_SENTRY_ENABLED:
        required: true
      WEBPACK_SENTRY_ORG:
        required: true
      WEBPACK_SENTRY_PROJECT:
        required: true
      WEBPACK_DEVTOOL:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Harbor login
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.HARBOR_URL}}
          username: ${{secrets.HARBOR_USER}}
          password: ${{secrets.HARBOR_PASSWORD}}

      - name: Setup SSH Agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          eval "$(ssh-agent -a $SSH_AUTH_SOCK > /dev/null)"
          ssh-add - <<< '${{ secrets.SSH_PRIVATE_KEY }}'

      - name: Build and push to Harbor
        uses: docker/build-push-action@v4
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          WEBPACK_SENTRY_AUTH_TOKEN: ${{secrets.WEBPACK_SENTRY_AUTH_TOKEN}}
          WEBPACK_SENTRY_ENABLED: ${{secrets.WEBPACK_SENTRY_ENABLED}}
          WEBPACK_SENTRY_ORG: ${{secrets.WEBPACK_SENTRY_ORG}}
          WEBPACK_SENTRY_PROJECT: ${{secrets.WEBPACK_SENTRY_PROJECT}}
          WEBPACK_DEVTOOL: ${{secrets.WEBPACK_DEVTOOL}}

        with:
          context: .
          ssh:
            default=${{ env.SSH_AUTH_SOCK }}
          build-args: REGISTRY_URL=${{secrets.HARBOR_URL}}/
          push: true
          tags:  ${{secrets.HARBOR_URL}}/${{inputs.APP_IMAGE_NAME}}:${{steps.package-version.outputs.current-version}}
