name: Deploy to heroku

on:
  workflow_call:
    inputs:
      heroku_app_name:
        required: true
        type: string
      heroku_email:
        required: true
        type: string

    secrets:
      heroku_api_key:
        required: true
      slack_webhook:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "[TEST]${{ steps.extract_branch.outputs.BRANCH }}"
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ inputs.heroku_app_name }}
          heroku_email: ${{ inputs.heroku_email }}
          dontautocreate: true
          dontuseforce: true
          branch: master

      - uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
          SLACK_USERNAME: Ship it, ship it now!
          SLACK_ICON_EMOJI: ":ship:"
          SLACK_FOOTER: ${{ github.repository }}
          SLACK_COLOR: ${{ job.status }}
          MSG_MINIMAL: actions url,message,commit
