name: Send on tests

on:
  workflow_call:
    inputs:
      result_emoji:
        required: true
        type: string
      action_url:
        required: true
        type: string

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print vars
        run: |
          echo "result_emoji ${{ inputs.result_emoji }}"
          echo "action_url ${{ inputs.action_url }}"
