name: terraform-apply

on:
  workflow_call:
    inputs:
        TERRAFORM_VERSION:
          required: true
          type: string
        CLOUD_PLATFORM:
          required: true
          type: string
        CLUSTER:
          required: true
          type: string
        CLUSTER_SHRINK:
          required: true
          type: boolean
    secrets:
        AWS_ACCESS_KEY_ID:
            required: true
        AWS_SECRET_ACCESS_KEY:
            required: true
        VKCLOUD_USERNAME:
            required: true
        VKCLOUD_PASSWORD:
            required: true

jobs:
  terraform-init-and-apply:
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
        run:
          working-directory: kubeClusters/${{ inputs.CLOUD_PLATFORM }}/${{ inputs.CLUSTER }}/terraform
    steps:
      
      - name: Git clone repo
        uses: actions/checkout@v3

      - name: Remove tf file for app node groups
        if: inputs.CLUSTER_SHRINK == true
        run: |
          rm -f apps_node_groups.tf
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.TERRAFORM_VERSION }}
            
      - name: Terraform Init
        run: terraform init -var 'vkcloud_username=${{ secrets.VKCLOUD_USERNAME }}' -var 'vkcloud_password=${{ secrets.VKCLOUD_PASSWORD }}' -var 'skip_credentials_validation=true' -var 'skip_region_validation=true'
      
      #- name: Terraform Apply
      #  run: terraform apply -auto-approve -var 'vkcloud_username=${{ secrets.VKCLOUD_USERNAME }}' -var 'vkcloud_password=${{ secrets.VKCLOUD_PASSWORD }}'

      #- name: Terraform Refresh
      #  run: terraform plan -refresh-only -var 'vkcloud_username=${{ secrets.VKCLOUD_USERNAME }}' -var 'vkcloud_password=${{ secrets.VKCLOUD_PASSWORD }}'

      - name: Terraform Import
        run: |
          terraform import -var 'vkcloud_username=${{ secrets.VKCLOUD_USERNAME }}' -var 'vkcloud_password=${{ secrets.VKCLOUD_PASSWORD }}' vkcs_kubernetes_cluster.k8s-cluster 3c414696-eeef-421f-9fff-1fa8b97ad14e 
          terraform import -var 'vkcloud_username=${{ secrets.VKCLOUD_USERNAME }}' -var 'vkcloud_password=${{ secrets.VKCLOUD_PASSWORD }}' vkcs_kubernetes_node_group.k8s-node-mini-node fb6a2de6-c086-439c-8e4d-76668d2b83a0 

      - name: Terraform Refresh
        run: terraform plan -refresh-only -var 'vkcloud_username=${{ secrets.VKCLOUD_USERNAME }}' -var 'vkcloud_password=${{ secrets.VKCLOUD_PASSWORD }}'

      - name: Terraform Plan
        run: terraform plan -var 'vkcloud_username=${{ secrets.VKCLOUD_USERNAME }}' -var 'vkcloud_password=${{ secrets.VKCLOUD_PASSWORD }}'
              